$cssFile = "src/Pages/LandingPage/Landingpagestyle.css"
$content = Get-Content $cssFile -Raw

# Replace all class names with landing- prefix
$content = $content -replace '\.header-top\b', '.landing-header-top'
$content = $content -replace '\bheader\s*\{', 'header.landing-header {'
$content = $content -replace '\.logo\b', '.landing-logo'
$content = $content -replace '\.hamburger\b', '.landing-hamburger'
$content = $content -replace '\.nav-menu\b', '.landing-nav-menu'
$content = $content -replace '\.nav-links\b', '.landing-nav-links'
$content = $content -replace '\.nav-link\b', '.landing-nav-link'
$content = $content -replace '\.item\b', '.landing-item'
$content = $content -replace '\.accountInfo\b', '.landing-accountInfo'
$content = $content -replace '\.user-info', '.landing-user-info'
$content = $content -replace '\.cart-icon\b', '.landing-cart-icon'
$content = $content -replace '\.hero\b', '.landing-hero'
$content = $content -replace '\.side_details\b', '.landing-side-details'
$content = $content -replace '\.btn-primary\b', '.landing-btn-primary'
$content = $content -replace '\.reliability\b', '.landing-reliability'
$content = $content -replace '\.feature\b', '.landing-feature'
$content = $content -replace '\.onsale\b', '.landing-onsale'
$content = $content -replace '\.carousel-container\b', '.landing-carousel-container'
$content = $content -replace '\.carousel-btn\b', '.landing-carousel-btn'
$content = $content -replace '\.prev-btn\b', '.landing-prev-btn'
$content = $content -replace '\.next-btn\b', '.landing-next-btn'
$content = $content -replace '\.cards-viewport\b', '.landing-cards-viewport'
$content = $content -replace '\.cards-container\b', '.landing-cards-container'
$content = $content -replace '\.no-products-message\b', '.landing-no-products-message'
$content = $content -replace '\.product-categories\b', '.landing-product-categories'
$content = $content -replace '\.category-tabs\b', '.landing-category-tabs'
$content = $content -replace '\.category-tab\b', '.landing-category-tab'
$content = $content -replace '\.category-content\b', '.landing-category-content'
$content = $content -replace '\.product-category-content\b', '.landing-product-category-content'
$content = $content -replace '\.product-item\b', '.landing-product-item'
$content = $content -replace '\.product-image\b', '.landing-product-image'
$content = $content -replace '\.product-details\b', '.landing-product-details'
$content = $content -replace '\.product-name\b', '.landing-product-name'
$content = $content -replace '\.product-price\b', '.landing-product-price'
$content = $content -replace '\.add-to-cart\b', '.landing-add-to-cart'

Set-Content $cssFile $content
Write-Host "CSS classes renamed successfully!"
